uci_administrador_indicelibro:
    pattern:  /lista_libros
    defaults: { _controller: UciAdministradorBundle:Libro:aIndiceLibro }
#
#uci_administrador_indicelibro:
#    pattern:  /lista_libros
#    defaults: { _controller: UciAdministradorBundle:Libro:index }
    
uci_administrador_nuevolibro:
    pattern:  /registrar_libro
    defaults: { _controller: UciAdministradorBundle:Libro:aRegistrarLibro }
    
uci_administrador_editarlibro:
    pattern:  /editat_libro
    defaults: { _controller: UciAdministradorBundle:Libro:aEditarLibro }
    
uci_administrador_deletelibro:
    pattern:  /admin/{id}/borrar_libro
    defaults: { _controller: UciAdministradorBundle:Libro:aBorrarLibro }
   
