uci_administrador_homepage:
    pattern:  /admin
    defaults: { _controller: UciAdministradorBundle:Default:aInicio }

uci_administrador_indiceuser:
    pattern:  /admin/lista_usuarios
    defaults: { _controller: UciAdministradorBundle:Usuario:aIndiceUsuario }
        
uci_administrador_adduser:
    pattern:  /admin/registrar_usuario
    defaults: { _controller: UciAdministradorBundle:Usuario:aRegistrarUsuario }
    
uci_administrador_edituser:
    pattern:  /admin/{id}/editar_usuario
    defaults: { _controller: UciAdministradorBundle:Usuario:aEditarUsuario }

uci_administrador_deleteuser:
    pattern:  /admin/{id}/borrar_usuario
    defaults: { _controller: UciAdministradorBundle:Usuario:aBorrarUsuario }
    
# ------------------------------CATEGORIA--------------------------------------------
    
uci_administrador_indicecategoria:
    pattern:  /admin/lista_categorias
    defaults: { _controller: UciAdministradorBundle:Categoria:aIndiceCategoria }
    
uci_administrador_addcategoria:
    pattern:  /admin/ingresar_generacion
    defaults: { _controller: UciAdministradorBundle:Categoria:aIngresarGeneracion }
    
uci_administrador_editcategoria:
    pattern:  /admin/{id}/editar_categoria
    defaults: { _controller: UciAdministradorBundle:Categoria:aEditarCategoria }

uci_administrador_addcategoria:
    pattern:  /admin/registrar_generacion
    defaults: { _controller: UciAdministradorBundle:Categoria:aIngresarGeneracion }
    
uci_administrador_deletecategoria:
    pattern:  /admin/{id}/borrar_categoria
    defaults: { _controller: UciAdministradorBundle:Categoria:aBorrarCategoria }

# ------------------------------CURSO--------------------------------------------

uci_administrador_indicecurso:
    pattern:  /admin/{id}/cursos_categoria
    defaults: { _controller: UciAdministradorBundle:Categoria:aIndiceCursos }
    
uci_administrador_addcurso:
    pattern:  /admin/{idGeneracion}/registrar_curso
    defaults: { _controller: UciAdministradorBundle:Categoria:aIngresarCurso }
    
uci_administrador_editcurso:
    pattern:  /admin/{idGeneracion}/editar_curso/{id}
    defaults: { _controller: UciAdministradorBundle:Categoria:aEditarCurso }
    
uci_administrador_deletecurso:
    pattern:  /admin/{idGeneracion}/borrar_curso/{id}
    defaults: { _controller: UciAdministradorBundle:Categoria:aBorrarCurso }
    
# ------------------------------CUESTIONARIO--------------------------------------------

uci_administrador_indicecuestionario:
    pattern:  /admin/indice_cuestionario
    defaults: { _controller: UciAdministradorBundle:Cuestionario:aIndiceCuestionario }
    
uci_administrador_registrarcuestionario:
    pattern:  /admin/construir_cuestionario
    defaults: { _controller: UciAdministradorBundle:Cuestionario:aConstruirCuestionario }
    
uci_administrador_setearlibroscuestionario:
    pattern:  /admin/setear_libro_cuestionario
    defaults: { _controller: UciAdministradorBundle:Cuestionario:aSetearLibrosCuestionario }
    
uci_administrador_guardarcuestionario:
    pattern:  /admin/guardar_cuestionario
    defaults: { _controller: UciAdministradorBundle:Cuestionario:aGuardarCuestionario }
    
uci_administrador_ver_cuestionario:
    pattern:  /admin/{id}/ver_cuestionario
    defaults: { _controller: UciAdministradorBundle:Cuestionario:aVerCuestionario }
    
uci_administrador_borrarCuestionario:
    pattern:  /admin/{idCuestionario}/borrar_cuestionario
    defaults: { _controller: UciAdministradorBundle:Cuestionario:aBorrarCuestionario }
   
#---------------------MATRICULAR USUARIO----------------------------------------

uci_administrador_matricularusuario:
    pattern:  /admin/{idGeneracion}/{idCurso}/matricular_usuario/{tipoUsuario}
    defaults: { _controller: UciAdministradorBundle:Categoria:matricularUsuario }

uci_administrador_desmatricularusuario:
    pattern:  /admin/{idGeneracion}/{idCurso}/desmatricular_usuario/{tipoUsuario}/{idUsuario}
    defaults: { _controller: UciAdministradorBundle:Categoria:aDesmatricularUsuario }
    
#---------------------PREGUNTAS-------------------------------------------------

uci_administrador_indicepreguntas:
    pattern:  /admin/ver_preguntas
    defaults: { _controller: UciAdministradorBundle:Pregunta:aIndicePregunta }
    
uci_administrador_eligeTipoPregunta:
    pattern:  /admin/elegir_tipo
    defaults: { _controller: UciAdministradorBundle:Pregunta:aElegirTipo }

uci_administrador_registrarPregunta:
    pattern:  /admin/{idTipoRespuesta}/registrar_pregunta
    defaults: { _controller: UciAdministradorBundle:Pregunta:aRegistrarPregunta }
    
uci_administrador_editarPregunta:
    pattern:  /admin/{idPregunta}/datos_libro
    defaults: { _controller: UciAdministradorBundle:Pregunta:aEditarPregunta }

uci_administrador_borrarRespuesta:
    pattern:  /admin/borrar_respuesta
    defaults: { _controller: UciAdministradorBundle:Pregunta:aBorrarRespuesta }

uci_administrador_borrarPregunta:
    pattern:  /admin/{idPregunta}/borrar_pregunta
    defaults: { _controller: UciAdministradorBundle:Pregunta:aBorrarPregunta }
    
uci_administrador_importarPreguntas:
    pattern:  /admin/importar_preguntas
    defaults: { _controller: UciAdministradorBundle:Pregunta:aImportarPreguntas }
    
#---------------------SOLICITUD-------------------------------------------------

uci_administrador_indicesolicitudes:
    pattern:  /admin/indice_solicitudes
    defaults: { _controller: UciAdministradorBundle:Solicitud:aIndiceSolicitud }
    
uci_administrador_addsolicitud:
    pattern:  /admin/agregar_solicitud
    defaults: { _controller: UciAdministradorBundle:Solicitud:aIngresarSolicitud }
    
uci_administrador_editsolicitud:
    pattern:  /admin/{id}/editar_solicitud
    defaults: { _controller: UciAdministradorBundle:Solicitud:aEditarSolicitud }
    
#---------------------Routing Libro---------------------------------------------
uci_administrador_libro:
    resource: "@UciAdministradorBundle/Resources/config/routing/libro.yml"
    prefix:   /admin/libro