uci_administrador_homepage:
    pattern:  /admin
    defaults: { _controller: UciAdministradorBundle:Default:aInicio }

uci_administrador_indiceuser:
    pattern:  /admin/lista_usuarios
    defaults: { _controller: UciAdministradorBundle:Default:aIndiceUsuario }
        
uci_administrador_adduser:
    pattern:  /admin/registrar_usuario
    defaults: { _controller: UciAdministradorBundle:Default:aRegistrarUsuario }