<?php

namespace Proxies\__CG__\Uci\Bundle\BaseDatosBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Libro extends \Uci\Bundle\BaseDatosBundle\Entity\Libro implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Libro' . "\0" . 'id', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Libro' . "\0" . 'titulo', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Libro' . "\0" . 'anio', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Libro' . "\0" . 'esPmbok', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Libro' . "\0" . 'idiomas', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Libro' . "\0" . 'pmbok');
        }

        return array('__isInitialized__', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Libro' . "\0" . 'id', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Libro' . "\0" . 'titulo', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Libro' . "\0" . 'anio', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Libro' . "\0" . 'esPmbok', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Libro' . "\0" . 'idiomas', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Libro' . "\0" . 'pmbok');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Libro $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPmbok(\Uci\Bundle\BaseDatosBundle\Entity\Pmbok $pmbok = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPmbok', array($pmbok));

        return parent::setPmbok($pmbok);
    }

    /**
     * {@inheritDoc}
     */
    public function getPmbok()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPmbok', array());

        return parent::getPmbok();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnio($anio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnio', array($anio));

        return parent::setAnio($anio);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnio', array());

        return parent::getAnio();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsPmbok($esPmbok)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsPmbok', array($esPmbok));

        return parent::setEsPmbok($esPmbok);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsPmbok()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsPmbok', array());

        return parent::getEsPmbok();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdiomas(\Uci\Bundle\BaseDatosBundle\Entity\Idiomas $idiomas = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdiomas', array($idiomas));

        return parent::setIdiomas($idiomas);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdiomas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdiomas', array());

        return parent::getIdiomas();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
