<?php

namespace Proxies\__CG__\Uci\Bundle\BaseDatosBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Curso extends \Uci\Bundle\BaseDatosBundle\Entity\Curso implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Curso' . "\0" . 'id', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Curso' . "\0" . 'nombrecurso', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Curso' . "\0" . 'asistenteAcademica', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Curso' . "\0" . 'solicitud', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Curso' . "\0" . 'generacion', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Curso' . "\0" . 'profesor');
        }

        return array('__isInitialized__', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Curso' . "\0" . 'id', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Curso' . "\0" . 'nombrecurso', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Curso' . "\0" . 'asistenteAcademica', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Curso' . "\0" . 'solicitud', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Curso' . "\0" . 'generacion', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Curso' . "\0" . 'profesor');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Curso $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombrecurso($nombrecurso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombrecurso', array($nombrecurso));

        return parent::setNombrecurso($nombrecurso);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombrecurso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombrecurso', array());

        return parent::getNombrecurso();
    }

    /**
     * {@inheritDoc}
     */
    public function addAsistenteAcademica(\Uci\Bundle\BaseDatosBundle\Entity\AsistenteAcademica $asistenteAcademica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAsistenteAcademica', array($asistenteAcademica));

        return parent::addAsistenteAcademica($asistenteAcademica);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAsistenteAcademica(\Uci\Bundle\BaseDatosBundle\Entity\AsistenteAcademica $asistenteAcademica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAsistenteAcademica', array($asistenteAcademica));

        return parent::removeAsistenteAcademica($asistenteAcademica);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsistenteAcademica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsistenteAcademica', array());

        return parent::getAsistenteAcademica();
    }

    /**
     * {@inheritDoc}
     */
    public function addSolicitud(\Uci\Bundle\BaseDatosBundle\Entity\Solicitud $solicitud)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSolicitud', array($solicitud));

        return parent::addSolicitud($solicitud);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSolicitud(\Uci\Bundle\BaseDatosBundle\Entity\Solicitud $solicitud)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSolicitud', array($solicitud));

        return parent::removeSolicitud($solicitud);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitud()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitud', array());

        return parent::getSolicitud();
    }

    /**
     * {@inheritDoc}
     */
    public function addGeneracion(\Uci\Bundle\BaseDatosBundle\Entity\Generacion $generacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGeneracion', array($generacion));

        return parent::addGeneracion($generacion);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGeneracion(\Uci\Bundle\BaseDatosBundle\Entity\Generacion $generacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGeneracion', array($generacion));

        return parent::removeGeneracion($generacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getGeneracion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeneracion', array());

        return parent::getGeneracion();
    }

    /**
     * {@inheritDoc}
     */
    public function addProfesor(\Uci\Bundle\BaseDatosBundle\Entity\Profesor $profesor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProfesor', array($profesor));

        return parent::addProfesor($profesor);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProfesor(\Uci\Bundle\BaseDatosBundle\Entity\Profesor $profesor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProfesor', array($profesor));

        return parent::removeProfesor($profesor);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesor', array());

        return parent::getProfesor();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
