Uci\Bundle\BaseDatosBundle\Entity\AreaConocimiento:
    type: entity
    table: area_conocimiento
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreArea:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: nombre_area
    manyToMany:
        pmbok:
            targetEntity: Pmbok
            cascade: {  }
            mappedBy: null
            inversedBy: areaConocimiento
            joinTable:
                name: pmbok_tiene_areas_conocimiento
                joinColumns:
                    -
                        name: area_conocimiento_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: pmbok_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
