Uci\Bundle\BaseDatosBundle\Entity\Bitacora:
    type: entity
    table: bitacora
    indexes:
        fk_bitacora_usuario1_idx:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        accion:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: accion
    manyToOne:
        usuario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
