Uci\Bundle\BaseDatosBundle\Entity\Capitulo:
    type: entity
    table: capitulo
    indexes:
        fk_Capitulo_PMBok_idx:
            columns:
                - libro_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
    fields:
        numeroCapitulo:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: numero_capitulo
        nombreCapitulo:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: nombre_capitulo
    oneToOne:
        libro:
            targetEntity: Libro
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                libro_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
