Uci\Bundle\BaseDatosBundle\Entity\Cuestionario:
    type: entity
    table: cuestionario
    indexes:
        fk_cuestionario_curso1_idx:
            columns:
                - curso_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        pruebaNumero:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: prueba_numero
        fecha:
            type: date
            nullable: false
            comment: ''
    manyToOne:
        curso:
            targetEntity: Curso
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                curso_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
