Uci\Bundle\BaseDatosBundle\Entity\CuestionarioTienePreguntas:
    type: entity
    table: cuestionario_tiene_preguntas
    indexes:
        fk_cuestionario_tiene_preguntas_cuestionario1_idx:
            columns:
                - cuestionario_id
        fk_cuestionario_tiene_preguntas_pregunta1_idx:
            columns:
                - pregunta_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ordenEnCuestionario:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: orden_en_cuestionario
    manyToOne:
        cuestionario:
            targetEntity: Cuestionario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cuestionario_id:
                    referencedColumnName: id
            orphanRemoval: false
        pregunta:
            targetEntity: Pregunta
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                pregunta_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
