Uci\Bundle\BaseDatosBundle\Entity\Cuestionario:
    type: entity
    table: cuestionario
    indexes:
        fk_cuestionario_curso1_idx:
            columns:
                - curso_id
  
    uniqueConstraints:
        cuestionarioname_UNIQUE:
            columns:
                - cuestionarioname
                
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cuestionarioname:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
        cantidadPreguntas:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: cantidad_preguntas
        aceptado:
            type: smallint
            nullable: false
            length: 1
            fixed: false
            comment: ''
            column: aceptado
        comentarioAceptado:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: comentario_aceptado
    manyToOne:
        curso:
            targetEntity: Curso
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                curso_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        pregunta:
            targetEntity: Pregunta
            cascade: {  }
            mappedBy: null
            inversedBy: cuestionario
            joinTable:
                name: cuestionario_tiene_preguntas
                joinColumns:
                    -
                        name: cuestionario_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    -
                        name: pregunta_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
