Uci\Bundle\BaseDatosBundle\Entity\Generacion:
    type: entity
    table: generacion
    uniqueConstraints:
        generacion_UNIQUE:
            columns:
                - generacion
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        generacion:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
    manyToMany:
        curso:
            targetEntity: Curso
            cascade: {  }
            mappedBy: null
            inversedBy: generacion
            joinTable:
                name: generacion_tiene_curso
                joinColumns:
                    -
                        name: generacion_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    -
                        name: curso_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
