Uci\Bundle\BaseDatosBundle\Entity\Pmbok:
    type: entity
    table: pmbok
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        edicion:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    manyToMany:
        areaConocimiento:
            targetEntity: AreaConocimiento
            cascade: {  }
            mappedBy: pmbok
            inversedBy: null
            joinTable: null
            orderBy: null
        trianguloTalento:
            targetEntity: TrianguloTalento
            cascade: {  }
            mappedBy: pmbok
            inversedBy: null
            joinTable: null
            orderBy: null
        grupoProcesos:
            targetEntity: GrupoProcesos
            cascade: {  }
            mappedBy: null
            inversedBy: pmbok
            joinTable:
                name: pmbok_tiene_grupo_procesos
                joinColumns:
                    -
                        name: pmbok_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: grupo_procesos_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
