Uci\Bundle\BaseDatosBundle\Entity\PreguntaTieneRespuestas:
    type: entity
    table: pregunta_tiene_respuestas
    indexes:
        fk_pregunta_tiene_respuestas_respuesta_idx:
            columns:
                - respuesta_id
        fk_pregunta_tiene_respuestas_pregunta1_idx:
            columns:
                - pregunta_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        orden:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    manyToOne:
        respuesta:
            targetEntity: Respuesta
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                respuesta_id:
                    referencedColumnName: id
            orphanRemoval: false
        pregunta:
            targetEntity: Pregunta
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                pregunta_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
