Uci\Bundle\BaseDatosBundle\Entity\Respuesta:
    type: entity
    table: respuesta
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        textoRespuesta:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: texto_respuesta
        textoRetroalimentacion:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: texto_retroalimentacion
    lifecycleCallbacks: {  }
