Uci\Bundle\BaseDatosBundle\Entity\Solicitud:
    type: entity
    table: solicitud
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        textosolicitud:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: textoSolicitud
        activa:
            type: smallint
            nullable: false
            length: 1
            fixed: false
            comment: ''
        modificada:
            type: smallint
            nullable: false
            length: 1
            fixed: false
            comment: ''
    manyToMany:
        curso:
            targetEntity: Curso
            cascade: {  }
            mappedBy: null
            inversedBy: solicitud
            joinTable:
                name: curso_tiene_solicitudes
                joinColumns:
                    -
                        name: solicitud_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: curso_id
                        referencedColumnName: id
            orderBy: null
        decano:
            targetEntity: Decano
            cascade: {  }
            mappedBy: solicitud
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
