Uci\Bundle\BaseDatosBundle\Entity\TipoPalabraFaltante:
    type: entity
    table: tipo_palabra_faltante
    indexes:
        fk_palabra_faltante_respuesta1_idx:
            columns:
                - respuesta_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        correcta:
            type: blob
            nullable: false
            length: 1
            fixed: false
            comment: ''
    manyToOne:
        respuesta:
            targetEntity: Respuesta
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                respuesta_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
