Uci\Bundle\BaseDatosBundle\Entity\TipoRespuestaMultiple:
    type: entity
    table: tipo_respuesta_multiple
    indexes:
        fk_respuesta_multiple_respuesta1_idx:
            columns:
                - respuesta_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        correcta:
            type: blob
            nullable: false
            length: 1
            fixed: false
            comment: ''
        porcentajeCorreccion:
            type: decimal
            nullable: true
            precision: 2
            scale: 0
            comment: ''
            default: '0'
            column: porcentaje_correccion
    manyToOne:
        respuesta:
            targetEntity: Respuesta
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                respuesta_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
