Uci\Bundle\BaseDatosBundle\Entity\Usuario:
    type: entity
    table: usuario
    indexes:
        fk_usuario_roles1_idx:
            columns:
                - rol_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        usuario:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        nombre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        apellidos:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
        clave:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        rol:
            targetEntity: Rol
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rol_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
