Uci\Bundle\BaseDatosBundle\Entity\Usuario:
    type: entity
    table: usuario
    indexes:
        fk_usuario_roles1_idx:
            columns:
                - rol_id
    uniqueConstraints:
        username_UNIQUE:
            columns:
                - username
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        apellidos:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
        username:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        salt:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        rol:
            targetEntity: Rol
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rol_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
