uci_principal:
    resource: "@UciSeguridadBundle/Resources/config/routing.yml"
    prefix:   /

uci_base_datos:
    resource: "@UciBaseDatosBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation



