uci_base_datos:
    resource: "@UciBaseDatosBundle/Resources/config/routing.yml"
    prefix:   /

uci_asistente_academica:
    resource: "@UciAsistenteAcademicaBundle/Resources/config/routing.yml"
    prefix:   /

uci_profesor:
    resource: "@UciProfesorBundle/Resources/config/routing.yml"
    prefix:   /

uci_decano:
    resource: "@UciDecanoBundle/Resources/config/routing.yml"
    prefix:   /

uci_administrador:
    resource: "@UciAdministradorBundle/Resources/config/routing.yml"
    prefix:   /

uci_principal:
    resource: "@UciSeguridadBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation



