# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
    
security:
    encoders:
        Uci\Bundle\BaseDatosBundle\Entity\Usuario:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
        
    providers:
        user_db:
            entity: { class: Uci\Bundle\BaseDatosBundle\Entity\Usuario, property: username }

    firewalls:    
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

       # login:
        #    pattern:  ^/login$
        #    security: false

        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path: /login
                check_path: /login_check
                use_referer: false
                remember_me: false
                always_use_default_target_path: true
                default_target_path: /login
            logout:
                path: /logout
                target: /admin
                invalidate_session: false
                delete_cookies:
                    name:
                    path: null
                    domain: null

    access_control:
      - { path: ^/admin, roles: ROLE_ADMINISTRADOR }
      - { path: ^/rol, roles: ROLE_ADMINISTRADOR }
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
      