# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
    
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Uci\BaseDatosBundle\Entity\Usuario: bcrypt
        
    providers:
        in_memory:
            memory: ~

    firewalls:
        main:
            pattern:
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
            security: true
            anonymous: true
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }