uci_profesor_homepage:
    path:     /profesor
    defaults: { _controller: UciProfesorBundle:Default:pInicio }
    
uci_profesor_edituser:
    pattern:  /profesor/{id}/editar_usuario
    defaults: { _controller: UciProfesorBundle:Usuario:pEditarUsuario }
    
# ------------------------------CUESTIONARIO--------------------------------------------

uci_profesor_indicecuestionario:
    pattern:  /profesor/indice_cuestionario
    defaults: { _controller: UciProfesorBundle:Cuestionario:pIndiceCuestionario }
    
uci_profesor_ver_cuestionario:
    pattern:  /profesor/{id}/ver_cuestionario
    defaults: { _controller: UciProfesorBundle:Cuestionario:pVerCuestionario }
    
uci_profesor_agregarComentarios:
    pattern:  /profesor/agregar_comentario
    defaults: { _controller: UciProfesorBundle:Cuestionario:pAgregarComentarioCuestionario }