<?php

namespace Proxies\__CG__\Uci\Bundle\BaseDatosBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Respuesta extends \Uci\Bundle\BaseDatosBundle\Entity\Respuesta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Respuesta' . "\0" . 'id', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Respuesta' . "\0" . 'textoRespuesta', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Respuesta' . "\0" . 'correcta', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Respuesta' . "\0" . 'extra', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Respuesta' . "\0" . 'textoRetroalimentacion', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Respuesta' . "\0" . 'pregunta');
        }

        return array('__isInitialized__', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Respuesta' . "\0" . 'id', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Respuesta' . "\0" . 'textoRespuesta', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Respuesta' . "\0" . 'correcta', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Respuesta' . "\0" . 'extra', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Respuesta' . "\0" . 'textoRetroalimentacion', '' . "\0" . 'Uci\\Bundle\\BaseDatosBundle\\Entity\\Respuesta' . "\0" . 'pregunta');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Respuesta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrden($orden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrden', array($orden));

        return parent::setOrden($orden);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrden', array());

        return parent::getOrden();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextoRespuesta($textoRespuesta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextoRespuesta', array($textoRespuesta));

        return parent::setTextoRespuesta($textoRespuesta);
    }

    /**
     * {@inheritDoc}
     */
    public function getTextoRespuesta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextoRespuesta', array());

        return parent::getTextoRespuesta();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextoRetroalimentacion($textoRetroalimentacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextoRetroalimentacion', array($textoRetroalimentacion));

        return parent::setTextoRetroalimentacion($textoRetroalimentacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTextoRetroalimentacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextoRetroalimentacion', array());

        return parent::getTextoRetroalimentacion();
    }

    /**
     * {@inheritDoc}
     */
    public function addPreguntum(\Uci\Bundle\BaseDatosBundle\Entity\Pregunta $pregunta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPreguntum', array($pregunta));

        return parent::addPreguntum($pregunta);
    }

    /**
     * {@inheritDoc}
     */
    public function removePreguntum(\Uci\Bundle\BaseDatosBundle\Entity\Pregunta $pregunta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePreguntum', array($pregunta));

        return parent::removePreguntum($pregunta);
    }

    /**
     * {@inheritDoc}
     */
    public function getPregunta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPregunta', array());

        return parent::getPregunta();
    }

    /**
     * {@inheritDoc}
     */
    public function getCorrecta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorrecta', array());

        return parent::getCorrecta();
    }

    /**
     * {@inheritDoc}
     */
    public function getExtra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtra', array());

        return parent::getExtra();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorrecta($correcta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorrecta', array($correcta));

        return parent::setCorrecta($correcta);
    }

    /**
     * {@inheritDoc}
     */
    public function setExtra($extra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtra', array($extra));

        return parent::setExtra($extra);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
