cuestionario:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:Cuestionario:index" }

cuestionario_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:Cuestionario:show" }

cuestionario_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:Cuestionario:new" }

cuestionario_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:Cuestionario:create" }
    methods:  POST

cuestionario_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:Cuestionario:edit" }

cuestionario_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:Cuestionario:update" }
    methods:  [POST, PUT]

cuestionario_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:Cuestionario:delete" }
    methods:  [POST, DELETE]
