cuestionarioasignadoausuario:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:CuestionarioAsignadoAUsuario:index" }

cuestionarioasignadoausuario_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:CuestionarioAsignadoAUsuario:show" }

cuestionarioasignadoausuario_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:CuestionarioAsignadoAUsuario:new" }

cuestionarioasignadoausuario_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:CuestionarioAsignadoAUsuario:create" }
    methods:  POST

cuestionarioasignadoausuario_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:CuestionarioAsignadoAUsuario:edit" }

cuestionarioasignadoausuario_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:CuestionarioAsignadoAUsuario:update" }
    methods:  [POST, PUT]

cuestionarioasignadoausuario_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:CuestionarioAsignadoAUsuario:delete" }
    methods:  [POST, DELETE]
