decano:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:Decano:index" }

decano_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:Decano:show" }

decano_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:Decano:new" }

decano_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:Decano:create" }
    methods:  POST

decano_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:Decano:edit" }

decano_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:Decano:update" }
    methods:  [POST, PUT]

decano_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:Decano:delete" }
    methods:  [POST, DELETE]
