generacion:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:Generacion:index" }

generacion_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:Generacion:show" }

generacion_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:Generacion:new" }

generacion_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:Generacion:create" }
    methods:  POST

generacion_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:Generacion:edit" }

generacion_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:Generacion:update" }
    methods:  [POST, PUT]

generacion_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:Generacion:delete" }
    methods:  [POST, DELETE]
