grupoprocesos:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:GrupoProcesos:index" }

grupoprocesos_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:GrupoProcesos:show" }

grupoprocesos_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:GrupoProcesos:new" }

grupoprocesos_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:GrupoProcesos:create" }
    methods:  POST

grupoprocesos_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:GrupoProcesos:edit" }

grupoprocesos_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:GrupoProcesos:update" }
    methods:  [POST, PUT]

grupoprocesos_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:GrupoProcesos:delete" }
    methods:  [POST, DELETE]
