idiomas:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:Idiomas:index" }

idiomas_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:Idiomas:show" }

idiomas_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:Idiomas:new" }

idiomas_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:Idiomas:create" }
    methods:  POST

idiomas_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:Idiomas:edit" }

idiomas_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:Idiomas:update" }
    methods:  [POST, PUT]

idiomas_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:Idiomas:delete" }
    methods:  [POST, DELETE]
