pmbok:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:Pmbok:index" }

pmbok_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:Pmbok:show" }

pmbok_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:Pmbok:new" }

pmbok_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:Pmbok:create" }
    methods:  POST

pmbok_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:Pmbok:edit" }

pmbok_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:Pmbok:update" }
    methods:  [POST, PUT]

pmbok_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:Pmbok:delete" }
    methods:  [POST, DELETE]
