pregunta:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:Pregunta:index" }

pregunta_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:Pregunta:show" }

pregunta_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:Pregunta:new" }

pregunta_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:Pregunta:create" }
    methods:  POST

pregunta_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:Pregunta:edit" }

pregunta_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:Pregunta:update" }
    methods:  [POST, PUT]

pregunta_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:Pregunta:delete" }
    methods:  [POST, DELETE]
