preguntatienerespuestas:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:PreguntaTieneRespuestas:index" }

preguntatienerespuestas_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:PreguntaTieneRespuestas:show" }

preguntatienerespuestas_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:PreguntaTieneRespuestas:new" }

preguntatienerespuestas_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:PreguntaTieneRespuestas:create" }
    methods:  POST

preguntatienerespuestas_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:PreguntaTieneRespuestas:edit" }

preguntatienerespuestas_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:PreguntaTieneRespuestas:update" }
    methods:  [POST, PUT]

preguntatienerespuestas_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:PreguntaTieneRespuestas:delete" }
    methods:  [POST, DELETE]
