profesor:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:Profesor:index" }

profesor_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:Profesor:show" }

profesor_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:Profesor:new" }

profesor_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:Profesor:create" }
    methods:  POST

profesor_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:Profesor:edit" }

profesor_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:Profesor:update" }
    methods:  [POST, PUT]

profesor_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:Profesor:delete" }
    methods:  [POST, DELETE]
