rol:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:Rol:index" }

rol_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:Rol:show" }

rol_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:Rol:new" }

rol_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:Rol:create" }
    methods:  POST

rol_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:Rol:edit" }

rol_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:Rol:update" }
    methods:  [POST, PUT]

rol_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:Rol:delete" }
    methods:  [POST, DELETE]
