solicitud:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:Solicitud:index" }

solicitud_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:Solicitud:show" }

solicitud_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:Solicitud:new" }

solicitud_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:Solicitud:create" }
    methods:  POST

solicitud_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:Solicitud:edit" }

solicitud_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:Solicitud:update" }
    methods:  [POST, PUT]

solicitud_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:Solicitud:delete" }
    methods:  [POST, DELETE]
