tiporespuestacorta:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:TipoRespuestaCorta:index" }

tiporespuestacorta_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:TipoRespuestaCorta:show" }

tiporespuestacorta_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:TipoRespuestaCorta:new" }

tiporespuestacorta_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:TipoRespuestaCorta:create" }
    methods:  POST

tiporespuestacorta_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:TipoRespuestaCorta:edit" }

tiporespuestacorta_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:TipoRespuestaCorta:update" }
    methods:  [POST, PUT]

tiporespuestacorta_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:TipoRespuestaCorta:delete" }
    methods:  [POST, DELETE]
