tipoprueba:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:TipoPrueba:index" }

tipoprueba_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:TipoPrueba:show" }

tipoprueba_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:TipoPrueba:new" }

tipoprueba_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:TipoPrueba:create" }
    methods:  POST

tipoprueba_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:TipoPrueba:edit" }

tipoprueba_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:TipoPrueba:update" }
    methods:  [POST, PUT]

tipoprueba_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:TipoPrueba:delete" }
    methods:  [POST, DELETE]
