tiporespuestamultiple:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:TipoRespuestaMultiple:index" }

tiporespuestamultiple_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:TipoRespuestaMultiple:show" }

tiporespuestamultiple_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:TipoRespuestaMultiple:new" }

tiporespuestamultiple_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:TipoRespuestaMultiple:create" }
    methods:  POST

tiporespuestamultiple_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:TipoRespuestaMultiple:edit" }

tiporespuestamultiple_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:TipoRespuestaMultiple:update" }
    methods:  [POST, PUT]

tiporespuestamultiple_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:TipoRespuestaMultiple:delete" }
    methods:  [POST, DELETE]
