tipopalabrafaltante:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:TipoPalabraFaltante:index" }

tipopalabrafaltante_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:TipoPalabraFaltante:show" }

tipopalabrafaltante_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:TipoPalabraFaltante:new" }

tipopalabrafaltante_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:TipoPalabraFaltante:create" }
    methods:  POST

tipopalabrafaltante_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:TipoPalabraFaltante:edit" }

tipopalabrafaltante_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:TipoPalabraFaltante:update" }
    methods:  [POST, PUT]

tipopalabrafaltante_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:TipoPalabraFaltante:delete" }
    methods:  [POST, DELETE]
