triangulotalento:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:TrianguloTalento:index" }

triangulotalento_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:TrianguloTalento:show" }

triangulotalento_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:TrianguloTalento:new" }

triangulotalento_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:TrianguloTalento:create" }
    methods:  POST

triangulotalento_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:TrianguloTalento:edit" }

triangulotalento_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:TrianguloTalento:update" }
    methods:  [POST, PUT]

triangulotalento_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:TrianguloTalento:delete" }
    methods:  [POST, DELETE]