usuariocorrigepregunta:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:UsuarioCorrigePregunta:index" }

usuariocorrigepregunta_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:UsuarioCorrigePregunta:show" }

usuariocorrigepregunta_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:UsuarioCorrigePregunta:new" }

usuariocorrigepregunta_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:UsuarioCorrigePregunta:create" }
    methods:  POST

usuariocorrigepregunta_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:UsuarioCorrigePregunta:edit" }

usuariocorrigepregunta_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:UsuarioCorrigePregunta:update" }
    methods:  [POST, PUT]

usuariocorrigepregunta_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:UsuarioCorrigePregunta:delete" }
    methods:  [POST, DELETE]
