usuario:
    path:     /
    defaults: { _controller: "UciBaseDatosBundle:Usuario:index" }

usuario_show:
    path:     /{id}/show
    defaults: { _controller: "UciBaseDatosBundle:Usuario:show" }

usuario_new:
    path:     /new
    defaults: { _controller: "UciBaseDatosBundle:Usuario:new" }

usuario_create:
    path:     /create
    defaults: { _controller: "UciBaseDatosBundle:Usuario:create" }
    methods:  POST

usuario_edit:
    path:     /{id}/edit
    defaults: { _controller: "UciBaseDatosBundle:Usuario:edit" }

usuario_update:
    path:     /{id}/update
    defaults: { _controller: "UciBaseDatosBundle:Usuario:update" }
    methods:  [POST, PUT]

usuario_delete:
    path:     /{id}/delete
    defaults: { _controller: "UciBaseDatosBundle:Usuario:delete" }
    methods:  [POST, DELETE]
