Uci\Bundle\DataBaseBundle\Entity\Curso:
    type: entity
    table: curso
    indexes:
        fk_curso_asistente_academica1_idx:
            columns:
                - asistente_academica_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        generacion:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        nombrecurso:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: nombreCurso
    manyToOne:
        asistenteAcademica:
            targetEntity: AsistenteAcademica
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                asistente_academica_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        cuestionario:
            targetEntity: Cuestionario
            cascade: {  }
            mappedBy: null
            inversedBy: curso
            joinTable:
                name: curso_tiene_cuestionarios
                joinColumns:
                    -
                        name: curso_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: cuestionario_id
                        referencedColumnName: id
            orderBy: null
        solicitud:
            targetEntity: Solicitud
            cascade: {  }
            mappedBy: curso
            inversedBy: null
            joinTable: null
            orderBy: null
        profesor:
            targetEntity: Profesor
            cascade: {  }
            mappedBy: curso
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
