Uci\Bundle\DataBaseBundle\Entity\GrupoProcesos:
    type: entity
    table: grupo_procesos
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreGrupo:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: nombre_grupo
        porcentaje:
            type: decimal
            nullable: false
            precision: 2
            scale: 0
            comment: ''
    manyToMany:
        pmbok:
            targetEntity: Pmbok
            cascade: {  }
            mappedBy: grupoProcesos
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
