Uci\Bundle\DataBaseBundle\Entity\Respuesta:
    type: entity
    table: respuesta
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        textoRespuesta:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: texto_respuesta
    manyToMany:
        pregunta:
            targetEntity: Pregunta
            cascade: {  }
            mappedBy: null
            inversedBy: respuesta
            joinTable:
                name: pregunta_tiene_respuestas
                joinColumns:
                    -
                        name: respuesta_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: pregunta_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
