Uci\Bundle\DataBaseBundle\Entity\TipoPrueba:
    type: entity
    table: tipo_prueba
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreTipo:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: nombre_tipo
    manyToMany:
        pregunta:
            targetEntity: Pregunta
            cascade: {  }
            mappedBy: tipoPrueba
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
