Uci\Bundle\DataBaseBundle\Entity\UsuarioRevisaCuestionarios:
    type: entity
    table: usuario_revisa_cuestionarios
    indexes:
        fk_revision_profesor_cuestionario_has_pregunta1_idx:
            columns:
                - cuestionario_tiene_pregunta_cuestionario_id
                - cuestionario_tiene_pregunta_pregunta_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fecha:
            type: date
            nullable: true
            comment: ''
        comentario:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        cuestionarioTienePreguntaCuestionario:
            targetEntity: CuestionarioTienePreguntas
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cuestionario_tiene_pregunta_cuestionario_id:
                    referencedColumnName: cuestionario_id
                cuestionario_tiene_pregunta_pregunta_id:
                    referencedColumnName: pregunta_id
            orphanRemoval: false
    manyToMany:
        usuario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: revisionUsuario
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
