uci_principal_homepage:
    pattern:  /
    defaults: { _controller: UciSeguridadBundle:Seguridad:index }
    requirements:
        _method:  GET

#Rutas para la autenticacion 

login:
    pattern: /login
    defaults: { _controller: UciSeguridadBundle:Seguridad:login }

login_check:
    pattern: /login_check
    defaults: { _controller: UciSeguridadBundle:Seguridad:loginCheck }

logout:
    pattern: /logout

