uci_base_datos_usuariocorrigepregunta:
    resource: "@UciBaseDatosBundle/Resources/config/routing/usuariocorrigepregunta.yml"
    prefix:   /usuariocorrigepregunta

uci_base_datos_usuario:
    resource: "@UciBaseDatosBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

uci_base_datos_tipoverdaderofalso:
    resource: "@UciBaseDatosBundle/Resources/config/routing/tipoverdaderofalso.yml"
    prefix:   /tipoverdaderofalso

uci_base_datos_tiporespuestamultiple:
    resource: "@UciBaseDatosBundle/Resources/config/routing/tiporespuestamultiple.yml"
    prefix:   /tiporespuestamultiple

uci_base_datos_tiporespuestacorta:
    resource: "@UciBaseDatosBundle/Resources/config/routing/tiporespuestacorta.yml"
    prefix:   /tiporespuestacorta

uci_base_datos_tiporespuesta:
    resource: "@UciBaseDatosBundle/Resources/config/routing/tiporespuesta.yml"
    prefix:   /tiporespuesta

uci_base_datos_tipoprueba:
    resource: "@UciBaseDatosBundle/Resources/config/routing/tipoprueba.yml"
    prefix:   /tipoprueba

uci_base_datos_tipopreguntanumerica:
    resource: "@UciBaseDatosBundle/Resources/config/routing/tipopreguntanumerica.yml"
    prefix:   /tipopreguntanumerica

uci_base_datos_tipopareo:
    resource: "@UciBaseDatosBundle/Resources/config/routing/tipopareo.yml"
    prefix:   /tipopareo

uci_base_datos_tipopalabrafaltante:
    resource: "@UciBaseDatosBundle/Resources/config/routing/tipopalabrafaltante.yml"
    prefix:   /tipopalabrafaltante

uci_base_datos_solicitud:
    resource: "@UciBaseDatosBundle/Resources/config/routing/solicitud.yml"
    prefix:   /solicitud

uci_base_datos_rol:
    resource: "@UciBaseDatosBundle/Resources/config/routing/rol.yml"
    prefix:   /rol

uci_base_datos_respuesta:
    resource: "@UciBaseDatosBundle/Resources/config/routing/respuesta.yml"
    prefix:   /respuesta

uci_base_datos_profesor:
    resource: "@UciBaseDatosBundle/Resources/config/routing/profesor.yml"
    prefix:   /profesor

uci_base_datos_preguntatienerespuestas:
    resource: "@UciBaseDatosBundle/Resources/config/routing/preguntatienerespuestas.yml"
    prefix:   /preguntatienerespuestas

uci_base_datos_pregunta:
    resource: "@UciBaseDatosBundle/Resources/config/routing/pregunta.yml"
    prefix:   /pregunta

uci_base_datos_pmbok:
    resource: "@UciBaseDatosBundle/Resources/config/routing/pmbok.yml"
    prefix:   /pmbok

uci_base_datos_libro:
    resource: "@UciBaseDatosBundle/Resources/config/routing/libro.yml"
    prefix:   /libro

uci_base_datos_idiomas:
    resource: "@UciBaseDatosBundle/Resources/config/routing/idiomas.yml"
    prefix:   /idiomas

uci_base_datos_grupoprocesos:
    resource: "@UciBaseDatosBundle/Resources/config/routing/grupoprocesos.yml"
    prefix:   /grupoprocesos

uci_base_datos_decano:
    resource: "@UciBaseDatosBundle/Resources/config/routing/decano.yml"
    prefix:   /decano

uci_base_datos_curso:
    resource: "@UciBaseDatosBundle/Resources/config/routing/curso.yml"
    prefix:   /curso

uci_base_datos_cuestionariotienepreguntas:
    resource: "@UciBaseDatosBundle/Resources/config/routing/cuestionariotienepreguntas.yml"
    prefix:   /cuestionariotienepreguntas

uci_base_datos_cuestionarioasignadoausuario:
    resource: "@UciBaseDatosBundle/Resources/config/routing/cuestionarioasignadoausuario.yml"
    prefix:   /cuestionarioasignadoausuario

uci_base_datos_cuestionario:
    resource: "@UciBaseDatosBundle/Resources/config/routing/cuestionario.yml"
    prefix:   /cuestionario

uci_base_datos_capitulo:
    resource: "@UciBaseDatosBundle/Resources/config/routing/capitulo.yml"
    prefix:   /capitulo

uci_base_datos_asistenteacademica:
    resource: "@UciBaseDatosBundle/Resources/config/routing/asistenteacademica.yml"
    prefix:   /asistenteacademica

uci_base_datos_areaconocimiento:
    resource: "@UciBaseDatosBundle/Resources/config/routing/areaconocimiento.yml"
    prefix:   /areaconocimiento

uci_base_datos_homepage:
    path:     /hello/{name}
    defaults: { _controller: UciBaseDatosBundle:Default:index }
